local servers = {
  ["angular"] = require'lspinstall/servers/angular',
  ["bash"] = require'lspinstall/servers/bash',
  ["cmake"] = require'lspinstall/servers/cmake',
  ["cpp"] = require'lspinstall/servers/cpp',
  ["csharp"] = require'lspinstall/servers/csharp',
  ["css"] = require'lspinstall/servers/css',
  ["deno"] = require'lspinstall/servers/deno',
  ["diagnosticls"] = require'lspinstall/servers/diagnosticls',
  ["dockerfile"] = require'lspinstall/servers/dockerfile',
  ["efm"] = require'lspinstall/servers/efm',
  ["elixir"] = require'lspinstall/servers/elixir',
  ["elm"] = require'lspinstall/servers/elm',
  ["go"] = require'lspinstall/servers/go',
  ["graphql"] = require'lspinstall/servers/graphql',
  ["html"] = require'lspinstall/servers/html',
  ["java"] = require'lspinstall/servers/java',
  ["json"] = require'lspinstall/servers/json',
  ["kotlin"] = require'lspinstall/servers/kotlin',
  ["latex"] = require'lspinstall/servers/latex',
  ["lua"] = require'lspinstall/servers/lua',
  ["php"] = require'lspinstall/servers/php',
  ["python"] = require'lspinstall/servers/python',
  ["rome"] = require'lspinstall/servers/rome',
  ["ruby"] = require'lspinstall/servers/ruby',
  ["rust"] = require'lspinstall/servers/rust',
  ["svelte"] = require'lspinstall/servers/svelte',
  ["tailwindcss"] = require'lspinstall/servers/tailwindcss',
  ["terraform"] = require'lspinstall/servers/terraform',
  ["typescript"] = require'lspinstall/servers/typescript',
  ["vim"] = require'lspinstall/servers/vim',
  ["vue"] = require'lspinstall/servers/vue',
  ["yaml"] = require'lspinstall/servers/yaml',
}

return servers
